[workspace]
members = [
"server",
"server-sdk",
"extension-sdk",
"extensions/etcd",
"extensions/postgresql",
"extensions/mysql",
"extensions/server",
"extensions/s3",
"extensions/nacos",
"extensions/kubernetes",
"extensions/cloudflare_pages",
"client",
]