name: Build and Release

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: client/package-lock.json

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y dos2unix protobuf-compiler libprotobuf-dev

    - name: Add execute permission
      working-directory: ./build
      run: chmod +x ./build.sh

    - name: Build
      working-directory: ./build
      run: ./build.sh

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        fail_on_unmatched_files: true
        files: |
          target/release/mould
          target/release/*.so
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}